//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCommunity.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GardenCommunityEntities : DbContext
    {
        public GardenCommunityEntities()
            : base("name=GardenCommunityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Indications> Indications { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Rates> Rates { get; set; }
    }
}
