//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenCommunity.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Id { get; set; }
        public System.DateTime DateOfPayment { get; set; }
        public double PaidFor { get; set; }
        public double ToPay { get; set; }
        public int MemberId { get; set; }
        public int RateId { get; set; }
    
        public virtual Indications Indications { get; set; }
        public virtual Members Members { get; set; }
        public virtual Rates Rates { get; set; }
    }
}
