// <auto-generated />
namespace GardenCommunity.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DataBase_created_13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataBase_created_13));
        
        string IMigrationMetadata.Id
        {
            get { return "201805061506401_DataBase_created_13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
